package sample;


import com.drools.models.Indvinfo;
import com.drools.models.PlanInfo;

rule "for ccap plan for DN"
  when
    IndvinfoObject: Indvinfo(marriedStatus=="N")
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("CCAP");
         pinfo.setPlanStatus("DN");
         pinfo.setMsg("Plan for child and you don't have child");
         IndvinfoObject.setPlanInfo(pinfo);
    end;
    
rule "for ccap plan for DN no child"
  when
    IndvinfoObject: Indvinfo(childStatus=="N")
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("CCAP");
         pinfo.setPlanStatus("DN");
         pinfo.setMsg("Plan for child and you don't have child");
         IndvinfoObject.setPlanInfo(pinfo);
    end;    
   
rule "for snap DN child is more than 3"
  when
    IndvinfoObject: Indvinfo(childCount>3)
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("CCAP");
         pinfo.setPlanStatus("DN");
         pinfo.setMsg("Many child you have, Plan is for only 1 to 3 child max");
         IndvinfoObject.setPlanInfo(pinfo);
   end;
   
 rule "for snap DN for child age more than 18+"
  when
    IndvinfoObject: Indvinfo(childAge>=18)
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("CCAP");
         pinfo.setPlanStatus("DN");
         pinfo.setMsg("Your child age is more than 18+ so plan is only allowed below 18+ age");
         IndvinfoObject.setPlanInfo(pinfo);
   end;
   
rule "for snap AP"
  when
    IndvinfoObject: Indvinfo(marriedStatus=="Y" && childStatus=="Y" && childCount<=3 && childAge<18)
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("CCAP");
         pinfo.setPlanStatus("AP");
         pinfo.setMsg("Congratulation..! your "+pinfo.getPlanName()+" is approved");
         IndvinfoObject.setPlanInfo(pinfo);
   end;