package com.rules;


import com.drl.model.Indvinfo;
import com.drl.model.PlanInfo;

rule "for snap plan AP for not Employed"
  when
    IndvinfoObject: Indvinfo(isEmployed=="N" && salary<=10000)
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("SNAP");
         pinfo.setPlanStatus("AP");
         IndvinfoObject.setPlanInfo(pinfo);
    end
    
rule "for snap plan AP for Employed with less salary"
  when
    IndvinfoObject: Indvinfo(isEmployee=="Y" && salary<=10000)
  then
         PlanInfo pinfo = new PlanInfo();
         pinfo.setPlanName("SNAP");
         pinfo.setPlanStatus("AP");
         IndvinfoObject.setPlanInfo(pinfo);
    end    
   
rule "for snap DN"
  when
    IndvinfoObject: Indvinfo(isEmployee=="Y" && salary>10000)
  then
      PlanInfo pinfo = new PlanInfo();
       pinfo.setPlanName("SNAP");
       pinfo.setPlanStatus("DN");
       pinfo.setDeniedReason("High Income");
       IndvinfoObject.setPlanInfo(pinfo);
   end